"""
hatch_build.py — Hatchling build hook: generate and fix protobuf stubs.

Runs during `pip install` (and `hatch build`) to regenerate the gateway
protobuf stubs from proto/gateway.proto into ros_core_client/ros2/proto/.

After generation, patches the bare `import gateway_pb2` in gateway_pb2_grpc.py
to a relative `from . import gateway_pb2` so the stubs work correctly when
installed as a package (the default protoc output uses absolute module names
which break inside a sub-package).
"""

import os
import sys

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class CustomBuildHook(BuildHookInterface):
    PLUGIN_NAME = "custom"

    def initialize(self, version, build_data):
        try:
            from grpc_tools import protoc
            import grpc_tools
        except ImportError:
            print(
                "WARNING: grpcio-tools is not installed. "
                "Skipping protobuf regeneration; using pre-generated stubs."
            )
            return

        proto_src = os.path.join(self.root, "proto", "gateway.proto")
        out_dir = os.path.join(self.root, "ros_core_client", "ros2", "proto")
        proto_include = os.path.join(self.root, "proto")
        grpc_include = os.path.join(grpc_tools.__path__[0], "_proto")

        if not os.path.isfile(proto_src):
            print(f"WARNING: proto source not found at {proto_src}, skipping generation.")
            return

        print(f"Generating protobuf stubs from {proto_src} → {out_dir}")

        ret = protoc.main([
            "grpc_tools.protoc",
            f"-I{proto_include}",
            f"-I{grpc_include}",
            f"--python_out={out_dir}",
            f"--grpc_python_out={out_dir}",
            proto_src,
        ])

        if ret != 0:
            raise RuntimeError(
                f"grpc_tools.protoc failed with exit code {ret}. "
                "Check that proto/gateway.proto is valid."
            )

        # Register the generated files with hatchling so they are included
        # in the wheel even though they are gitignored.
        # force_include maps absolute source path → relative dest in wheel.
        for fname in ("gateway_pb2.py", "gateway_pb2_grpc.py"):
            build_data["force_include"][os.path.join(out_dir, fname)] = (
                f"ros_core_client/ros2/proto/{fname}"
            )

        # Fix the absolute import generated by protoc so it works inside
        # the ros_core_client.ros2.proto package without sys.path tricks.
        #
        # protoc generates:   import gateway_pb2 as gateway__pb2
        # We need:            from . import gateway_pb2 as gateway__pb2
        grpc_stub = os.path.join(out_dir, "gateway_pb2_grpc.py")
        if os.path.isfile(grpc_stub):
            with open(grpc_stub, "r", encoding="utf-8") as fh:
                content = fh.read()

            fixed = content.replace(
                "import gateway_pb2 as gateway__pb2",
                "from . import gateway_pb2 as gateway__pb2",
            )

            if fixed != content:
                with open(grpc_stub, "w", encoding="utf-8") as fh:
                    fh.write(fixed)
                print("  Patched relative import in gateway_pb2_grpc.py")
            else:
                print("  gateway_pb2_grpc.py already uses relative import — no patch needed.")

        print("Protobuf generation complete.")
