# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: relay_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'relay_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13relay_service.proto\x12\x0cgrpc_objects\x1a\x1fgoogle/protobuf/timestamp.proto\"v\n\x15\x43ommandRequestMessage\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tnode_name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\x12\x0f\n\x07request\x18\x04 \x01(\x0c\"\x99\x01\n\x16\x43ommandResponseMessage\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tnode_name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\r\x12\x10\n\x08response\x18\x06 \x01(\x0c\x32n\n\x0fRpcCommunicator\x12[\n\x0e\x45xecuteCommand\x12#.grpc_objects.CommandRequestMessage\x1a$.grpc_objects.CommandResponseMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'relay_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDREQUESTMESSAGE']._serialized_start=70
  _globals['_COMMANDREQUESTMESSAGE']._serialized_end=188
  _globals['_COMMANDRESPONSEMESSAGE']._serialized_start=191
  _globals['_COMMANDRESPONSEMESSAGE']._serialized_end=344
  _globals['_RPCCOMMUNICATOR']._serialized_start=346
  _globals['_RPCCOMMUNICATOR']._serialized_end=456
# @@protoc_insertion_point(module_scope)
